package common

import "strings"

// ACLTagPrefix is the reserved tag namespace that marks a resource's content as
// restricted by a LimaCharlie resource ACL. A resource carrying the tag
// "acl:<scope>" is only readable by principals holding the scope <scope>.
const ACLTagPrefix = "acl:"

// Known values for ACL.Source. They are informational only and never affect
// the access decision.
const (
	ACLSourceUser         = "user"         // A user or API key made the request directly.
	ACLSourceImpersonated = "impersonated" // The request was made on behalf of another principal.
	ACLSourceDR           = "dr"           // The request originates from a D&R rule action.
	ACLSourceContinuation = "continuation" // The request is a continuation the extension asked for.
	ACLSourceInternal     = "internal"     // The request was generated by the platform itself.
)

// ACL is the platform-set block that LimaCharlie attaches to every request
// envelope. It describes what the initiator of the request is allowed to see
// with respect to resource ACLs (resources tagged "acl:<scope>").
//
// It is set by the platform at the top level of the request envelope, never
// inside the user-controlled Data, and is covered by the same HMAC signature
// as the rest of the body. An extension should never trust an "acl" value found
// anywhere else.
type ACL struct {
	// Scopes is the list of ACL scope names the initiator holds in the org,
	// without the "acl:" prefix.
	Scopes []string `json:"scopes" msgpack:"scopes"`
	// Global is true when the initiator holds "access.global" and is therefore
	// allowed to access every resource regardless of its ACL tags.
	Global bool `json:"global" msgpack:"global"`
	// Enforce is true when the org has at least one enabled ACL scope. When it
	// is false, no resource in the org is restricted and the extension may
	// skip every ACL check for this request.
	Enforce bool `json:"enforce" msgpack:"enforce"`
	// Source describes where the request came from (see the ACLSource*
	// constants). It is informational only.
	Source string `json:"source" msgpack:"source"`
}

// ACLView is the read-only view of the ACL block that request handlers receive.
//
// It is always usable, even when the envelope did not carry an ACL block
// (for example when talking to an older LimaCharlie extension manager). In
// that case Present() is false and the view FAILS CLOSED for extensions that
// enforce ACLs: Scopes is nil, Global is false and Enforce is true, so
// Allows returns false for any resource carrying an "acl:" tag and true for
// resources without one. This way an extension can never leak a restricted
// resource just because the platform did not tell it what the initiator holds.
type ACLView struct {
	// Scopes, Global, Enforce and Source mirror the fields of ACL.
	Scopes  []string
	Global  bool
	Enforce bool
	Source  string

	present bool
}

// NewACLView builds the view handed to request handlers from the block carried
// by the envelope. A nil block yields the fail-closed default described on
// ACLView.
func NewACLView(a *ACL) ACLView {
	if a == nil {
		return ACLView{
			Scopes:  nil,
			Global:  false,
			Enforce: true,
			present: false,
		}
	}
	return ACLView{
		Scopes:  a.Scopes,
		Global:  a.Global,
		Enforce: a.Enforce,
		Source:  a.Source,
		present: true,
	}
}

// Present reports whether the request envelope actually carried an ACL block.
// When false, the view holds the fail-closed default.
func (v ACLView) Present() bool {
	return v.present
}

// Envelope returns the ACL block as it was received on the envelope, or nil if
// the envelope did not carry one. It is meant for intermediaries (such as the
// multiplexer) that need to forward the request to another extension without
// altering what the platform said.
func (v ACLView) Envelope() *ACL {
	if !v.present {
		return nil
	}
	return &ACL{
		Scopes:  v.Scopes,
		Global:  v.Global,
		Enforce: v.Enforce,
		Source:  v.Source,
	}
}

// Allows reports whether the initiator of the request may access a resource
// carrying the given tags.
//
// The rules are:
//   - Global initiators are allowed everywhere.
//   - When Enforce is false, no resource is restricted and everything is allowed.
//   - Otherwise every "acl:<scope>" tag on the resource must name a scope the
//     initiator holds (AND rule). A bare "acl:" tag or a scope the initiator
//     does not hold locks the resource. Tags outside the "acl:" namespace are
//     ignored.
//
// Tags and scope names are compared case-insensitively with surrounding
// whitespace trimmed, and a single entry containing commas is treated as a
// list of tags (the platform's tag list separator).
//
// Allows only ever restricts: it is the second half of a decision and must be
// combined with the extension's normal permission checks, never used to grant
// access the org permissions would not already allow.
func (v ACLView) Allows(tags []string) bool {
	if v.Global {
		return true
	}
	if !v.Enforce {
		return true
	}
	var held map[string]struct{}
	for _, entry := range tags {
		for _, tag := range strings.Split(entry, ",") {
			scope, ok := ACLScopeFromTag(tag)
			if !ok {
				continue
			}
			if held == nil {
				held = make(map[string]struct{}, len(v.Scopes))
				for _, s := range v.Scopes {
					held[NormalizeACLScope(s)] = struct{}{}
				}
			}
			if _, isHeld := held[scope]; !isHeld {
				return false
			}
		}
	}
	return true
}

// NormalizeACLScope normalizes a scope name (or a tag) the way the platform
// does: lowercased and trimmed of surrounding whitespace.
func NormalizeACLScope(scope string) string {
	return strings.ToLower(strings.TrimSpace(scope))
}

// ACLScopeFromTag returns the normalized scope name carried by an "acl:" tag.
// The boolean is false for tags outside the "acl:" namespace. It is true for a
// bare "acl:" tag, which yields an empty scope name; since no scope can be named
// "", such a tag always locks the resource in ACLView.Allows.
func ACLScopeFromTag(tag string) (string, bool) {
	n := NormalizeACLScope(tag)
	if !strings.HasPrefix(n, ACLTagPrefix) {
		return "", false
	}
	return strings.TrimSpace(n[len(ACLTagPrefix):]), true
}
